server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/AuthDB
    username: prod_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
