server:
  port: 8083

spring:
  application:
    name: EMPLOYEE-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/EmployeeService
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.example.employeeservice.FeignClient: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true